# Capítulo 04 - Básico sobre o NumPy: arrays e processamento vetorizado

## Nota [80]

NumPy - _Numerical Python_, é um dos pacotes básicos mais importantes para processamento numérico em Python. Oferece uma API fácil de usar e passa facilmente dados para bibliotecas externas escritas em linguagem de baixo nível, valendo o mesmo para biblitecas devolverem dados ao Python como arrays NumPy.

Apesar do NumPy por si só não oferecr funcionalidades científicas nem de modelgem, compreender os arrays NumPy e o processamento orientado a arrays ajudará na utilização de ferramentas com semântica orientada a arrays, como o pandas. Este capítulo irá percorrer os váris tópicos de NumPy, deixando um modo mais detalhado para os capítulos futuros.

Existe vários fatores que tornam NumPy uma ferramenta importante para processamento numéricos em Python, mas o principal é o fato dele ter sido projetado para ser eficaz em arrays de dados grandes, pois ele armazena dados em bloco contíguo de memória. Os arrays NumPy também utilizam muito menos memória que as sequências embutidas de Python. Em muitos casos realizam processamentos complexos sem a necessidade de laços `for`.

In [1]:
# Imports
import numpy as np

In [2]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

Vamos multiplicar cada sequência por 2:

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 42.3 ms, sys: 27.8 ms, total: 70.1 ms
Wall time: 68.4 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 456 ms, sys: 168 ms, total: 625 ms
Wall time: 623 ms


Algoritmos baseados no NumPy geralmente são de 10 a 100 vezes mais rápidos do que suas contrapartidas em Python puro, e utilizam menos memória.

## O ndarray do NumPy: um objeto array multidimensional Parte-I

Um dos principais recursos do NumPy é seu objeto array N-dimensional, ou `ndarray`, que é um contêiner rápido e flexível para conjuntos de dados grandes em Python, permitindo realizar operações matemáticas em blocos inteiros de dados usando uma sintaxe semelhante às operações equivalentes entre blocos escalares.

In [5]:
# Gera alguns dados aleatórios
data = np.random.randn(2, 3)
data

array([[-0.61431332,  0.0894226 ,  1.90074565],
       [ 0.75583666, -0.36000279,  1.12402779]])

In [6]:
data * 10

array([[-6.14313315,  0.89422601, 19.0074565 ],
       [ 7.55836657, -3.60002792, 11.24027795]])

In [7]:
data + data

array([[-1.22862663,  0.1788452 ,  3.8014913 ],
       [ 1.51167331, -0.72000558,  2.24805559]])

No primeiro exemplo todos os dados foram multiplicados por 10, no segundo, os valores correspondentes em cada "célula" do array foram somanos uns aos outros.

<div style="border:2px solid #17a2b8; padding:10px; background-color:#d1ecf1; border-radius:5px;">
🔎 <b>Observação:</b> Usaremos por convenção neste capítulo e nos seguintes <code>import numpy as np</code>. Evitaremos <code>from numpy import *</code> pois o namespace __numpy__ é extenso e contém uma série de funções cujos nomes entram em conflito com funções embutidas Python (como <i>min</i> e <i>max</i>)
</div>


Um ndarray é um cntêiner genérico multidimensional para dados homogêneos; isso significa que todos os elementos devem ser do mesmo tipo. Todo array tem um _shape_, isto é, uma tupla que indica o tamanho de cada dimensão, e um _dtype_, que é um objeto que descreve o _tipo de dado_ do array:

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

<div style="border:2px solid #17a2b8; padding:10px; background-color:#d1ecf1; border-radius:5px;">
🔎 <b>Observação:</b> Sempreque tivermos "array", "NumPy array" ou "ndarray", salvo poucas exceções, todos eles se referirão ao mesmo item: o objeto ndarray.
</div>

### Criando ndarrays

A maneira mais fácil de criar um array é usar a função `array`. Ela aceita qualquer objeto do tipo sequência (incluindo outros arrays) e gera um novo array NumPy contendo os dados recebidos:

In [10]:
data1 = [6, 7.5, 8, 0, 1]

arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

Sequências aninhadas, como uma lista de listas de mesmo tamanho, serão convertidas em um array multidimensional:

In [11]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Como `data2` era uma lista de listas, o array NumPy `arr2` tem duas dimensões, com o formato inferido a partir dos dados. Podemos confirmar isso inspecionando os atributos _ndim_ e _shape_:

In [12]:
arr2.ndim

2

In [13]:
arr2.shape

(2, 4)

A menos que esteja explicitamente especificado, `np.array` tentará inferir um _bom tipo de dado_ para o array que ele criar. O tipo de dado é armazenado em um objeto especial de metadados __dtype__:

In [14]:
arr1.dtype

dtype('float64')

In [15]:
arr2.dtype

dtype('int64')

Além de `np.array`, há uma série de outras funções para criar novos arrays. Como exemplos, `zeros` e `ones` criam arrays de 0s ou de 1s respectivamente, com um dado tamanho ou formato. `empty` cria um array sem inicializar seus valores com qualquer valor em particular. Para criar um array com dimensões maires usando esses métodos, passe uma tupla para o formato:

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
np.empty((2, 3, 2))

array([[[          nan,  1.61886e-319],
        [          nan,  3.23781e-319],
        [-0.00000e+000,  8.09477e-320]],

       [[-0.00000e+000,  8.06315e-320],
        [-0.00000e+000,  4.94066e-324],
        [ 4.94066e-324,  0.00000e+000]]])

<div style="border:2px solid #ffc107; padding:10px; background-color:#fff3cd; border-radius:5px;">
⚠️ <b>Aviso:</b> Não é seguro supor que <code>np.empty</code> devolverá um array somente comzeros. Em alguns casos (como no nosso), valores "lixos" não inicializados poderão ser devolvidos
</div>

`arange` é uma versão da função embutida `range` de Python com valores de arrat:

In [19]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**Funções para criação de arrays**

| Função | Descrição |
|--------|-----------|
| array | Converte os dados de entrada (sequência) em um ndarray, seja inferino um dtype ou especificando-o expicitamente; copia os dados de entrada, por padrão |
| asarray | Converte a entrada para um ndarray, mas não copia se a entrada já fou um ndarray |
| arange | Como a função embutida `range`, porém devolve um ndarray em vez de uma lista |
| ones, one_like | Gera um array somente com 1s, com formato e o dtype especificado; `ones_like` aceita outro array e gera um array de 1s com o mesmo formato e dtype |
| zeros, zeros_like | Como `ones` e `ones_like`, porém gerando arrays com 0s |
| empty, empty_like | Cria novos arrays alocando nova memória, mas não preenche com nenhum valor, como `ones` e `zeros` |
| full, full_like | Gera um array com o formato e o dtype especificados, com todos os valores definidos com o "valor de preenchimento" indicados. `full_like` aceita outro array e gera um array preenchido com o mesmo formato e o mesmo dtype |
| eye, identity | Cria  uma matriz-identidade quadrada N x N (1s na diagonal e 0s nas demais posições |

### Tipos de dados para ndarray

0 _tipo de dado_ ou `dtype` é um objeto especial contendo as informações que o ndarray precisa para interpretar uma porção de memória como um tipo de dado particular:

In [20]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

arr2 = np.array([1, 2, 3], dtype=np.int32)

In [21]:
arr1.dtype

dtype('float64')

In [22]:
arr2.dtype

dtype('int32')

Os __dtypes__ são um dos motivos para a flexibilidade do NumPy em interagir com ados provenientes de outros sistemas. Os __dtypes__ numéricos recebem o nome da mesma maneira: um nome de tipo como `float` oou `int`, seguido de um número que indica a quantidade de bits por elemento.

**Tipos de dados do NumPy**

| Tipo | Códigodo tipo | Descrição|
|------|---------------|----------|
| int8, uint8 |  i1, u1 | Tipos inteiros de 8 bits com e sem sinal |
| int16, uint16 | i2, u2 | Tipos inteiros de 16 bits com e sem sinal |
| int32, uint32 | i4, u4 | Tipos inteiros de 32 bits com e sem sinal |
| int64, uint64 | i8, u8 | Tipos inteiros de 64 bits com e sem sinal |
| float16 | f2 | Ponto flutuante com metade da precisão |
| float32 | f4 ou f | Ponto flutuante padrão com precisão única; compatível com o float de C |
| float64 | f8 ou d | Ponto flutuante padrão com dupla precisão; compatível com o double de C e o objeto `float` do Python |
| float128 | f16 ou g | Ponto flutuante com precisão extendida |
| complex64, complex128, complex256 | c8, c16, c32 | Números complexos representados por dois floats de 32 e 64 pu 126, respectivamente |
| boll | ? | Tipo booleano que armazena os valores `True` e `False` |
| object | O | Tipo objeto de Python; um valor pode ser qualquer objeto de Python |
| string_ | S | Tipo string ASCII de tamanho fixo (1 byte por caractere); por exemplo, para criar um dtype string com tamanho 10, utilize 'S10' |
| unicode_ | U | Tipo Unicode de tamanho fixo (número de bytes é especifico de cada plataforma); a mesma semântica de especificação de `string_` (por exemplo, 'U10') |

Podemos converter explicitamente ou fazer _cast_ de um array de um dtype para outro usando o método `astype` de ndarray:

In [23]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [24]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

Se fizermos o cast de algum número de ponto flutuante para um  dtype inteiro, a parte decimal será truncada:

In [25]:
arr = np.array([3.17, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.17, -1.2 , -2.6 ,  0.5 , 12.9 , 10.1 ])

In [26]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

Se for um array de strings que representam números, pode usar `astype` para convertê-lo em um formato númerico:

In [27]:
numeric_strings = np.array(["1.25", "-9.6", "42"])
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

Perceba que usei `float` ao invés de `np.float64`, isso porque o NumPy tem aliases para os tipos Python, para os seus prórpios dtypes equivalentes.

<div style="border:2px solid #ffc107; padding:10px; background-color:#fff3cd; border-radius:5px;">
⚠️ <b>Aviso:</b>  É importante ser cauteloso ao usar o tipo <code>numpy.string_</code> , pois dados de string no Numpy têm tamaho fixo e podem truncar os dados de entrada sem avisos. O pandas tem um coportamento próprio ais intuitivo para dados não numéricos.
</div>

In [28]:
int_array = np.arange(10)

calibers = np.array([0.22, 0.270, 0.357, 0.380, 0.44, 0.50], dtype=np.float64)

In [29]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

Podemos usar os códigos (strings) de tipos de dados do NumPy (ver Tabela acima), e que podem ser usadas para se referir a um dtype:

In [30]:
empty_uint32 = np.empty(8, dtype="u4")
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

<div style="border:2px solid #17a2b8; padding:10px; background-color:#d1ecf1; border-radius:5px;">
🔎 <b>Observação:</b> Chamar <code>astype</code> <i>sempre</i> cria um novo array (uma cópia de dados), mesmo que o novo dtype seja igual ao dtype antigo.
</div>

### Aritmética com arrays NumPy

Arrays são importantes porque permitem expressar operações em lote nos dados, sem escrever qualquer laço `for`. Os usuários do NumPy chamam isso de _vetorização_. Qualquer operação aritmética entre arrays de mesmo tamanho faz a operação ser aplicada a __todos os elementos__:

In [31]:
arr = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [32]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [33]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

Operações aritméticas com escalares fazem o argumento escalar ser propagado a cada elemento do array:

In [34]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [35]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

As comparações entre arrays do mesmo tamanho resultam em arrays booleans:

In [36]:
arr2 = np.array([[0.0, 4.0, 1.0], [7.0, 2.0, 12.0]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [37]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

Operações entre arrays de tamanhos distintos são chamadas de _brodcasting_ e serão discutidas com mais detalhes no Apêndice A. Ter um conhecimento profundo de broadcasting não é necessário no aprofundamento dos nossos estudos neste curso.

### Indexação básia e fatiamento

Arrays unidimensional são simples; superficialmente, eles se comportam de modo semelhante às listas de Python:

In [38]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr[5]

np.int64(5)

In [40]:
arr[5:8]

array([5, 6, 7])

In [41]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

Ao atribuir um valor escalar a uma fatia, como em `arr[5:8] = 12`, o valor será propagado (sofre broadcasting) para toda seleção. Fatias de arrays são _visualizações_ do array original, ou seja, os dados não são copiados, e qualquer modificação na visualização se refletirá no array original.

In [42]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

Agora, quando altero valores em `arr_slice`, as mudanças se refletem no array `arr` original:

In [43]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

A fatia "nua" `[:]` fará uma atribuição a todos os valore em um array:

In [44]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

<div style="border:2px solid #ffc107; padding:10px; background-color:#fff3cd; border-radius:5px;">
⚠️ <b>Aviso:</b> Se vicê quiser uma cópia de uma fatia de um ndarray em vez de ter uma visualização, será necessário copiar explicitamente o array - por exemplo, <code>arr[5:8].copy()</code>.
</div>

Com arrays de dimensões maiores, você tem muito mais opções. Em um array bidimensional, os elementos em cada índice não são mais escalares, mas são arrays unidimensionais:

In [45]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

Desse modo, os elementos individuais podem ser acessados recursivamente. Entretanto, isso exige um pouco de trabalho, portanto podemos passar uma lista de índices separados por vírgula para selecionar elementos individuais. Assim, as instruções a seguir são equivalentes:

In [46]:
arr2d[0][2]

np.int64(3)

In [47]:
arr2d[0, 2]

np.int64(3)

Em arrays multidimensionais, se você omitir os índices finais, o objeto devolvido será um ndarray de dimensões menores, constiituído de todos os dados nas dimensões mais altas. Assim, no array __arr3d 2 x 2 x 3:

In [48]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

`arr3d[0]` é um array 2 x 3

In [49]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

Tantos valores escalares quanto arrays podem ser atribuídos a `arr3d[0]`

In [50]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [51]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

De mod semelhante , `arr3d[1, 0]` contém todos os valores cujos índices começam com (1, 0), formando um array unidimensional:

In [52]:
arr3d[1, 0]

array([7, 8, 9])

Essa expressão é equivalente a uma indexação em dois passos:

In [53]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [54]:
x[0]

array([7, 8, 9])

## C04B01 | Correção/análise técnica do notebook (Nota 0–100)

Escopo analisado
- Notebook: C04B01.ipynb
- Tema: NumPy básico (ndarray, criação, dtype/astype, aritmética vetorizada, indexação e fatiamento)
- Dependências externas: nenhuma (somente `import numpy as np`)

Rubrica (fixa) + nota por critério
1) Execução e reprodutibilidade (20%): 85  -> 17.00 pts
   - Ponto forte: não depende de arquivos externos.
   - Ajuste sugerido: usar `np.random.seed(...)` antes de `np.random.randn(...)` para tornar saídas reproduzíveis.
   - Observação: células com `%time` exigem ambiente IPython/Jupyter (ok para notebook, falha fora dele).

2) Correção técnica do código e lógica (25%): 92 -> 23.00 pts
   - Exemplos e explicações batem com o comportamento real do NumPy (vetorização, casts, slices como views, etc.).

3) Organização e legibilidade do notebook (15%): 80 -> 12.00 pts
   - Fluxo didático coerente e incremental.
   - Ajuste sugerido: evitar reutilizar o nome `arr` para coisas diferentes (ex.: `arr_1d`, `arr_2d`, `arr_3d`) para reduzir ambiguidade.

4) Texto/PT-BR e comunicação (10%): 60 -> 6.00 pts
   - Há muitos erros de digitação/ortografia que atrapalham leitura e passam sensação de “rascunho”.
   - Exemplos: “biblitecas”, “Indexação básia”, “brodcasting”, “vicê”, “tamaho”, “Códigodo”, etc.
   - Tabela: “ones, one_like” deveria ser “ones, ones_like”.

5) Análise e interpretação (15%): 73 -> 10.95 pts
   - Bom para introdução; pouca “interpretação” porque o material é majoritariamente tutorial (o que é esperado aqui).
   - Ajuste sugerido: em 1–2 pontos, adicionar mini-conclusões (ex.: “quando usar view vs copy” e “impacto de dtype em memória”).

6) Boas práticas e higiene (10%): 80 -> 8.00 pts
   - Uso adequado de exemplos mínimos e alertas (especialmente sobre `np.empty` e strings fixas).
   - Ajuste sugerido: padronizar nomes/evitar sobrescrever variáveis sem necessidade.

7) Profundidade (5%): 70 -> 3.50 pts
   - Cobre o essencial; não entra em tópicos como boolean indexing, fancy indexing, reshape/broadcasting na prática (ok para B01).

Nota Técnica (B1)
- Total: 80.45 / 100  (arred.: 80)

Parecer técnico consolidado
- Código está correto e didático. O principal gargalo é qualidade textual (muitos typos) e pequenos detalhes de nomenclatura/consistência.
- Se você corrigir os erros de texto + ajustar “ones_like” na tabela + definir seed para o exemplo aleatório, esse notebook sobe fácil para a faixa 85–90 no B1.
