# Capítulo 04 - Básico sobre o NumPy: arrays e processamento vetorizado

## O ndarray do NumPy: um Objeto array multimencional Parte-II

### Indexando com fatias

Assim como os objetos unidimensionais, por exemplo, as listas Python,os ndarrays podem ser fatiados com a sintaxe conhecida:

In [1]:
# imports para estudos
import numpy as np

In [2]:
arr = np.array([0, 1, 2, 3, 4, 64, 64, 64, 8, 9])
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [3]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

Considere o array bidimensional `arr2d`, fatiar esse array é um pouco diferente:

In [4]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 9, 0]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 9, 0]])

In [5]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

Com podemos ver, ele foi fatiado ao longo do eixo 0, que é o primeiro eixo. Uma fatia, portanto, seleciona um intervalo de elementos ao longo de um eixo. Ler a expressão `arr2d[:2]` como "selecione as duas primeiras linhas de `arr2d`" talvez possa ajudar.

Podemos passar várias fatias, do mesmo modo como podemos passar vários índices:

In [6]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

Ao fatiar dessa maneira, sempre vamos obter visualizações do array com o mesmo número de dimensões. Ao combinar índices inteiros com fatias, teremos fatias de dimensões menores.

Por exemplo, posso selecionar a segunda linha, mas somente as duas primeiras colunas, assim:

In [7]:
arr2d[1, :2]

array([4, 5])

De modo semelhante, podemos selecionar a terceira coluna, mas somente as duas primeiras linhas, da seguinte forma:

In [9]:
arr2d[:2, 2]

array([3, 6])

É claro que fazer uma atribuição a uma expressão de fatia faz a atribuição para toda a seleção:

In [10]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 9, 0]])

### Indexação booleana

Vamos considerar um exemplo em que temos alguns dados em um array e um array de nomes com duplicatas.

In [18]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [17]:
np.random.seed(1986)
data = np.random.randn(7, 4)
data

array([[-0.77697904,  0.12661351,  0.84873769,  0.23162548],
       [ 1.83053336,  0.40549799,  1.57478167, -1.18232321],
       [ 1.11513844,  0.96935128,  0.97029393,  0.6014799 ],
       [ 0.96444816, -0.80939013, -0.58440423, -1.81105921],
       [-2.09184252,  1.64182189,  0.92775316,  0.18360477],
       [-0.14779428, -1.57900133, -0.43353833,  0.69764212],
       [-1.08862086, -0.10519027, -0.37086476,  1.99636946]])

Suponha que cada nome corresponda a uma linha do array `data` e que queremos selecionar todas as linhas com o nome correspondenete 'Bob'. Assim como nas operações aritméticas, as comparações (como ==) com arrays também são vetorizadas. Assim, comparar `names` com a string 'Bob' produzirá um array _booleano_:

In [19]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

Esse array booleano pode ser passado quando o array é indexado:

In [20]:
data[names == "Bob"]

array([[-0.77697904,  0.12661351,  0.84873769,  0.23162548],
       [ 0.96444816, -0.80939013, -0.58440423, -1.81105921]])

O array booleano deve ter o mesmo tamanho do eixo do array que ele está indexando. Você pode até mesmo misturar e fazer a correspondência entre arrays booleanos e fatias ou inteiro.

<div style="border:2px solid #ffc107; padding:10px; background-color:#fff3cd; border-radius:5px;">
⚠️ <b>Aviso: A seleção booleana não falhará se o array booleano não tiver o tamanho correto, portanto recomendo tomar cuidado quando utilizar esse recurso.</b> 
</div>
</br>

Nesses exemplos, faremos a seleção a partir das linhas em que `names == "Bob"' e indexo as colunas também:

In [21]:
data[names == "Bob", 2]

array([ 0.84873769, -0.58440423])

In [22]:
data[names == "Bob", 3]

array([ 0.23162548, -1.81105921])

Para selecionar tudo exceto 'Bob', podemos usar `!=` ou negar a condição uando `~`:

In [23]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [24]:
data[~(names == "Bob")]

array([[ 1.83053336,  0.40549799,  1.57478167, -1.18232321],
       [ 1.11513844,  0.96935128,  0.97029393,  0.6014799 ],
       [-2.09184252,  1.64182189,  0.92775316,  0.18360477],
       [-0.14779428, -1.57900133, -0.43353833,  0.69764212],
       [-1.08862086, -0.10519027, -0.37086476,  1.99636946]])

O operador `~` pode ser útil e quisermos inverter uma condição genérica:

In [25]:
cond = names == "Bob"

data[~cond]

array([[ 1.83053336,  0.40549799,  1.57478167, -1.18232321],
       [ 1.11513844,  0.96935128,  0.97029393,  0.6014799 ],
       [-2.09184252,  1.64182189,  0.92775316,  0.18360477],
       [-0.14779428, -1.57900133, -0.43353833,  0.69764212],
       [-1.08862086, -0.10519027, -0.37086476,  1.99636946]])

Selecionando dois dos três nomes para combinar várias condições booleanas, utilize operadores aritméticos booleanos como `&` (and) e `|` (or):

In [27]:
mask = (names == "Bob") | (names == "Will")
mask

array([ True, False,  True,  True,  True, False, False])

In [28]:
data[mask]

array([[-0.77697904,  0.12661351,  0.84873769,  0.23162548],
       [ 1.11513844,  0.96935128,  0.97029393,  0.6014799 ],
       [ 0.96444816, -0.80939013, -0.58440423, -1.81105921],
       [-2.09184252,  1.64182189,  0.92775316,  0.18360477]])

Selecione dados de um array com indexação booleana _sempre_ criará uma cópia dos dados, mesmo que o array devolvido não seja alterado.

<div style="border:2px solid #ffc107; padding:10px; background-color:#fff3cd; border-radius:5px;">
⚠️ <b>Aviso: As palavras reservadas and e or de Python não funcionam com arrays booleans. Utilize & (and) e | (or) em seu lugar.</b> 
</div>
</br>

Definir valores com arrays booleanos funciona de acordo com o senso comum. Para definir todos os valores negativos em `data` com 0, basta fazer o seguinte:

In [29]:
data[data < 0] = 0
data

array([[0.        , 0.12661351, 0.84873769, 0.23162548],
       [1.83053336, 0.40549799, 1.57478167, 0.        ],
       [1.11513844, 0.96935128, 0.97029393, 0.6014799 ],
       [0.96444816, 0.        , 0.        , 0.        ],
       [0.        , 1.64182189, 0.92775316, 0.18360477],
       [0.        , 0.        , 0.        , 0.69764212],
       [0.        , 0.        , 0.        , 1.99636946]])

Definir linhas ou colunas inteiras uando um array booleano unidimensional também é fácil:

In [30]:
data[names != "Joe"] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.83053336, 0.40549799, 1.57478167, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.69764212],
       [0.        , 0.        , 0.        , 1.99636946]])

Como veremos mais adiante, esses tipos de operações em dados, bidimensionais são covenientes para serem executados com o pandas.

### Indexação sofisticada

_Indexação sofisticada_ (fancy indexing) é o termo adotado pelo NumPy para descrever a indexação usando arrays de inteiros especificando a ordem desejada:

In [32]:
# reatribuição de arr
arr = np.empty((8, 4))
arr

array([[7.70386764e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 5.02034658e+175, 9.96234736e-047,
        4.81582738e-038],
       [1.22545376e-046, 2.21509243e-056, 4.30866401e-033,
        4.25850025e-096],
       [1.12855837e+277, 8.93168725e+271, 4.76484771e+180,
        1.70098498e+256],
       [5.49109388e-143, 5.77243674e+228, 1.35617292e+248,
        3.36163259e-067],
       [5.00535704e-090, 1.78675734e-051, 3.79278748e+179,
        5.75088688e-066],
       [5.28555805e+180, 1.24449159e-047, 4.57134917e-071,
        3.25746029e-086],
       [3.35560313e-143, 9.30350598e+199, 4.24941018e-086,
        4.05171181e-317]])

In [33]:
for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

Para selecionar um subconjunto das linhas em uma ordem em particular, podemos simplesmente passar uma lista ou um ndarray de inteiros especificando a ordem desejada:

In [34]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [35]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

Passar vários índices de array faz algo um pouco diferente; a instrução seleciona um array unidimensional de elementos correspondentes a cada tupla de índices:

In [36]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [37]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

Nesse caso, os elementos(1,0),(5,3),(7,1) e (2,2) foram selecionados. Independentemente de quantas dimensões o array tiver, o resultado da indexação sofisticada sempre será unidimensional.

O comportamento da indexação sofisticada nesse caso é um pouco diferente do que alguns usuários poderiam esperar, que é a região retangular formada pela seleção de um subconjunto das linhas e colunas da matriz. Eis uma forma de obter isso:

In [38]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

Tenha em mente que a indexação sofisticada, de modo diferente do fatiamento, sempre copia os dados para um novo array.

### Transposição de arrays e troca de eixos

A transposição é uma forma especial de reformatação que, de modo semelhante, devolve uma visualização dos dados subjacentes, sem copiar nada. Os arrays têm o método `transpose`, além do atributo especial T:

In [39]:
# reatribuição de arr
arr = np.arange(15).reshape(3, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [40]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

Ao fazer processamento de matrizes ,talvez você realize isto com muita frequência - por exemplo, quando calcular o produto da matriz interna usando `np.dot`:

In [41]:
np.random.seed(1986)
arr1 = np.random.randn(6, 3)
arr1

array([[-0.77697904,  0.12661351,  0.84873769],
       [ 0.23162548,  1.83053336,  0.40549799],
       [ 1.57478167, -1.18232321,  1.11513844],
       [ 0.96935128,  0.97029393,  0.6014799 ],
       [ 0.96444816, -0.80939013, -0.58440423],
       [-1.81105921, -2.09184252,  1.64182189]])

In [42]:
np.dot(arr1.T, arr1)

array([[ 8.28702173,  2.41211271, -1.76344708],
       [ 2.41211271, 10.73715936, -2.84652433],
       [-1.76344708, -2.84652433,  5.52720354]])

Para arrays de dimensões maiores, `transpose` aceitará uma tupla de números de eixos para permutá-los:

In [43]:
arr2 = np.arange(16).reshape(2, 2, 4)
arr2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [44]:
arr2.transpose(1, 0, 2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

Nesse caso, os eixos foram reordenados com o segundo eixo em primeiro lugar, o primeiro eixo em segundo e o último eixo permanexeu inlaterado.

Uma transposição simples com `.T` é um caso especial de troca de eixos. O ndarray tem p método `swapaxes`, que aceita um par de números de eixos e troca os eixos indicados para reorganizar os dados:

In [45]:
arr2.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

De modo semelhante, `swapaxes`devolve uma visualização dos dados, sem criar uma cópia.

## C04B02 — Registro do bloco + correção/análise técnica (Nota 0–100)

Rubrica (pesos do CORE)
1) Execução e reprodutibilidade (20%): 20/20
- Todas as células executam sem erro; não há dependências externas.
- Há `np.random.seed(...)` nos trechos com aleatoriedade.

2) Correção técnica do código e lógica (25%): 19/25
- Código consistente com a proposta (slice, boolean indexing, fancy indexing, transpose/dot).
- Há 2 afirmações conceituais incorretas no texto (ver achados [ALTO]).

3) Organização e legibilidade do notebook (15%): 13/15
- Sequência didática por seções está boa, exemplos progressivos.
- Pequenas melhorias: evitar “re-atribuições” repetidas sem aviso (arr/arr2d) ou marcar explicitamente “redefinição”.

4) Texto/PT-BR e comunicação (10%): 7/10
- Vários typos/ortografia e alguns trechos truncados/quebrados (exemplos abaixo).

5) Análise e interpretação (15%): 11/15
- Explica o “como”, mas faltam reforços de “efeitos” (shape/result, view vs copy) em alguns pontos-chave.

6) Boas práticas e higiene (10%): 9/10
- `import numpy as np`, exemplos limpos, seeds usados.
- Melhorar consistência de nomes e evitar reaproveitar variáveis sem contexto.

7) Profundidade (5%): 3/5
- Cobertura correta no geral; faltou nuance em: compatibilidade de máscara booleana e comportamento dimensional da indexação sofisticada.

Nota Técnica (B1): 82/100

Achados (3–7) com severidade
[ALTO] Aviso diz: “A seleção booleana não falhará se o array booleano não tiver o tamanho correto”.
- Incorreto: máscara booleana precisa ser compatível com o eixo indexado (senão gera erro), salvo casos em que você transforma a forma explicitamente (ex.: `mask[:, None]`).

[ALTO] Texto diz: “o resultado da indexação sofisticada sempre será unidimensional”.
- Incorreto: depende do padrão de indexação. Ex.: `arr[[4,3,0,6]]` (seleção de linhas) preserva colunas → resultado 2D; já `arr[[1,5,7,2],[0,3,1,2]]` (pares de coordenadas) retorna 1D.

[MÉDIO] Trechos com truncamento/typos atrapalham leitura (principalmente em explicações).
- Exemplos: “multimencional”, “Com podemos ver”, “uando”, “covenientes”.

[BAIXO] Reatribuições sequenciais (`arr = ...`) podem confundir quem volta para revisar.
- Sugestão: nomes por seção (`arr_slice`, `arr_bool`, `arr_fancy`) ou comentário “redefinindo arr para o próximo exemplo”.

Typos/ajustes de escrita (amostra)
- “multimencional” → “multidimensional”
- “Com podemos ver” → “Como podemos ver”
- “uando” → “quando”
- “covenientes” → “convenientes”
- “um Objeto array” → “um objeto array”
- Revisar quebras de linha em frases longas (há trechos cortados no meio).

3 ações recomendadas (curtas e acionáveis)
1) Corrigir as 2 afirmações conceituais [ALTO] e adicionar 1 exemplo curto de “máscara incompatível → erro” + 1 exemplo de fancy indexing retornando 2D.
2) Padronizar nomes de variáveis por seção e sinalizar explicitamente quando um array é redefinido.
3) Fazer uma passada de revisão textual (ortografia + frases truncadas) e garantir que cada seção termina com 1–2 bullets de “resultado esperado” (shape/dtype/view vs copy).

Observação de processo
- Rubrica e pesos seguem o CORE (B1). 
