# Capítulo 04 - Básico sobre NumPy: arrats e processamento vetorizao

## Funções universais: funções rápidas de arrays para todos os elementos

Uma função universal, ou _ufunc_, é uma função que executa operaçoes em todos os elementos nos dados de ndarrays. Podemos pensar nelas como _wrappers_ vetorizados rápidos para funções simples que aceitam um ou mais valores escalares e geram um ou mais resultados escalares.

Muitas funções são transformações simples em todos os elementos, como _sqrt_ ou _exp_:

In [1]:
# imports
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

Essasfunções são chamadas de _ufuncs unárias_. Outras, como `add` ou `maximun`, aceitam dois arrays e devolvem um único array como resultado:

In [5]:
np.random.seed(1986)
x = np.random.randn(8)
x

array([-0.77697904,  0.12661351,  0.84873769,  0.23162548,  1.83053336,
        0.40549799,  1.57478167, -1.18232321])

In [8]:
np.random.seed(2026)
y = np.random.randn(8)
y

array([-0.43171852, -1.39287397,  0.31157067, -0.01323488,  1.44970773,
        0.29815274, -0.82989603, -1.59615853])

In [9]:
np.maximum(x, y)

array([-0.43171852,  0.12661351,  0.84873769,  0.23162548,  1.83053336,
        0.40549799,  1.57478167, -1.18232321])

Neste caso, `numpy.maximum` calculou o máximo entre os elementos de x e y para todos os elementos.

Embora não seja comum, uma ufunc pode devolver vários arrays. `modf` é um exemplo; ela é uma versão vetorizada da função embutida `divmod` de Python e devolve as partes fracionárias e inteira de um array de ponto flutuante:

In [10]:
np.random.seed(1990)
arr1 = np.random.randn(7) * 5
arr1

array([-1.91162906,  1.00446972,  7.80880126, -1.31883602, -2.91819024,
        6.12064346, -1.60220359])

In [12]:
remainder, whole_part = np.modf(arr1)

remainder

array([-0.91162906,  0.00446972,  0.80880126, -0.31883602, -0.91819024,
        0.12064346, -0.60220359])

In [13]:
whole_part

array([-1.,  1.,  7., -1., -2.,  6., -1.])

As ufuncs aceitam um argumento opcinal _out_ que lhes permite atuar _in-place_ns arrays:

In [15]:
arr1

array([-1.91162906,  1.00446972,  7.80880126, -1.31883602, -2.91819024,
        6.12064346, -1.60220359])

In [19]:
np.sqrt(arr1)

array([       nan, 1.00055763, 1.29292415,        nan,        nan,
       1.25415044,        nan])

In [18]:
np.sqrt(arr1, arr1)

array([       nan, 1.00111556, 1.67165285,        nan,        nan,
       1.57289333,        nan])

In [20]:
arr1

array([       nan, 1.00111556, 1.67165285,        nan,        nan,
       1.57289333,        nan])

**Ufuncs unárias**
| Função | Descrição |
|--------|-----------|
| abs, fabs | Calcula o valor absoluto de inteiros, números de ponto flutuante e valores cmplexos para todos os elementos |
| sqrt | Calcula a raiz quadrada de cada elemento |
| square | Calcula o quadrado de cada elemento |
| exp | Calcula o exponencial $e^x$ de cada elemento |
| log, log10, log2, log1p | Logaritmo natural, na base 10, na base 2 e ($1 + x$), respectivamente |
| sign | Calcula o sinal de cada elemento: 1 (positivo), 0 (zero) ou -1(negativo) |
| ceil | Calcula o teto de cada elemento |
| floor | Calcula o piso de cada elemento |
| rint | Arredonda os elementos para o inteiro mais próximo, preservando o _dtype_ |
| modf | Devolve as partes fracinárias e inteira do array como um array separado |
| isnan | Devolve um array booleano indicando se cada valor é __NaN__ |
| isfinite, isinf | Devolve um array booleano indicando se cada elemento é finito ou infinito, respectivamente |
| cos, cosh, sin, sinh, tan, tanh | Funções trigonométricas regulares e hiperbólicas |
| arccos, arccosh, arcsin, arcsinh, arctan, arctanh | Funções trigonométricas inversas |
| logical_not | Calcula o valor-verdade de _not x_ para todos os elementos |

**Funções universais binárias**
| Função | Descrição |
|--------|-----------|
| add | Soma elementos correspondentes em arrays |
| subtract | Subtrai elementos do segundo array do primeiro |
| multiply | Multiplica elementos do array |
| divide, floor_divide | Faz a divisão ou a divisão pelo piso (truncando o resto) |
| power | Elevaos elementos do primeiro array às potências indicadas no segundo array |
| maximun, fmax | Máximo para todos os elementos; __fmax__ ignora __NaN__ |
| minimum, fmin | Mínimo para todos os elementos; __fmin__ ignora __NaN__ |
| mod | Módulo para todos os elementos (resto da divisão) |
| copysign | Copia o sinal dos valores do segundo argumento para os valores do primeiro argumento |
| greater, greater_equal, less, less_equal, equal, not_equal | Faz uma comparação para todos os elementos, produzindo um array booleano |
|logical_and, logical_or, logical_xor | Calcula o valor-verdade da operação lógica para todos os elementos |

# B1 — C04B03 — Correção/análise técnica do notebook (Nota 0–100)

## 1) Resultado
Nota B1: **74.00 / 100** (2 casas, truncamento)

Dependências externas: **não há** (somente NumPy).  
Execução: **todas as células executam** (há 1 *RuntimeWarning* esperado em `sqrt` com valores negativos).

## 2) Rubrica B1 (fixa) — pontuação por critério
| Critério | Peso | Nota (0–100 no critério) | Contribuição |
|---|---:|---:|---:|
| Execução e reprodutibilidade | 20% | 95.00 | 19.00 |
| Correção técnica do código e lógica | 25% | 80.00 | 20.00 |
| Organização e legibilidade do notebook | 15% | 80.00 | 12.00 |
| Texto/PT-BR e comunicação | 10% | 40.00 | 4.00 |
| Análise e interpretação | 15% | 53.33 | 8.00 |
| Boas práticas e higiene | 10% | 80.00 | 8.00 |
| Profundidade | 5% | 60.00 | 3.00 |
**Total:** 74.00

## 3) Achados (3–7) com severidade
[ALTO] `np.sqrt(arr1)` com `arr1` contendo valores negativos gera `RuntimeWarning` e produz `nan` para esses elementos. O notebook mostra isso, mas não explica o motivo nem o impacto (principalmente antes do exemplo `out` in-place).

[MÉDIO] Uso do parâmetro `out` (`np.sqrt(arr1, arr1)`) modifica `arr1` **in-place** e “perde” os valores originais. Isso é correto, mas falta reforçar a implicação (ex.: se precisa do original, faça cópia antes).

[MÉDIO] Texto está com muitos typos/quebras, reduzindo a qualidade didática e a confiança na explicação (ver amostra abaixo).

[BAIXO] Reprodutibilidade: há `seed` para `x`, `y`, `arr1` (bom), mas falta padronizar o racional do porquê seeds diferentes (ex.: “exemplos independentes”).

[BAIXO] A tabela final de “Ufuncs unárias” está extensa/truncada no notebook e sem fechamento/continuidade clara (parece colada e interrompida).

## 4) Typos/ajustes de escrita (amostra)
- “arrats” → “arrays”
- “vetorizao” → “vetorizado”
- “Uma função unive...” → completar a frase
- “Essasfunções” → “Essas funções”
- “maximun” → “maximum” (no texto)
- “opcinal” → “opcional”
- “_in-place_ns” → “in-place nos”
- “cmplex” → “complexos”

## 5) 3 ações recomendadas (curtas e acionáveis)
1) Inserir 2–4 linhas explicando `sqrt` em negativos: por que ocorre `nan`/warning e alternativas (ex.: `np.sqrt(np.abs(x))` apenas como demonstração, ou filtrar `arr1[arr1>=0]` quando fizer sentido).
2) Antes do exemplo `out` in-place, adicionar um aviso explícito: “isso sobrescreve o array; faça `arr1_copy = arr1.copy()` se precisar do original”.
3) Fazer revisão textual rápida (ortografia + completar frases truncadas) e padronizar headings/descrições para fechar a narrativa (especialmente antes da tabela final).

