# C04B01 Avaliação bloco 

## Nota [ ]

Instruções: crie e responda em `C04B01_TEST.ipynb`. Use apenas `import numpy as np`. Para cada questão: uma célula Markdown com a resposta curta (quando pedido) e uma célula de código com a execução.

Q1 (10 pts) — Reprodutibilidade com seed

* (a) Defina `np.random.seed(123)` e gere `data1 = np.random.randn(2, 3)`.
* (b) Redefina `np.random.seed(123)` e gere `data2 = np.random.randn(2, 3)`.
* (c) Mostre (via comparação) que `data1` e `data2` são iguais.
* (d) Mude a seed e gere `data3`; mostre que difere.

Q2 (10 pts) — Inferência de dtype e casting na criação

* (a) Crie `arr = np.array([6, 7.5, 8, 0, 1])` e mostre `arr` e `arr.dtype`.
* (b) Em Markdown: explique por que o dtype foi esse.
* (c) Crie `arr_int = np.array([6, 7.5, 8, 0, 1], dtype=np.int32)` e mostre `arr_int`. Explique o que aconteceu com o `7.5`.

Q3 (10 pts) — Criação: zeros/ones/empty

* (a) Crie `z = np.zeros((3, 6))`, `o = np.ones(10)`, `e = np.empty((2, 3, 2))`.
* (b) Para cada um, mostre `shape`, `ndim`, `dtype`.
* (c) Em Markdown: diga quando `empty` faz sentido e qual a pegadinha.

Q4 (10 pts) — `arange` + slicing + atribuição por slice

* (a) Crie `arr = np.arange(15)`.
* (b) Faça `arr[5:8] = 12`.
* (c) Mostre `arr` antes/depois e descreva em 1–2 linhas o que ocorreu.

Q5 (10 pts) — View vs copy

* (a) Crie `a = np.arange(10)`; `s = a[2:6]`; faça `s[:] = -1`. Mostre `a` e `s`.
* (b) Crie `b = np.arange(10)`; `t = b[2:6].copy()`; faça `t[:] = -1`. Mostre `b` e `t`.
* (c) Em Markdown: explique por que o resultado de (a) e (b) difere.

Q6 (10 pts) — Aritmética vetorizada
Com `v = np.array([1, 2, 3, 4])`, calcule e mostre:

* (a) `v * v`
* (b) `v - v`
* (c) `1 / v`
* (d) `v ** 0.5`

Q7 (10 pts) — Operações com escalares em 2D (broadcast escalar)

* (a) Crie `m = np.array([[1,2,3],[4,5,6]])`.
* (b) Calcule `m + 10` e `m * 0.1`.
* (c) Mostre os resultados e seus `shape`s.

Q8 (10 pts) — Comparações elemento-a-elemento

* (a) Crie `a = np.array([[1,2,3],[4,5,6]])` e `b = np.array([[0,2,4],[4,4,7]])`.
* (b) Calcule `a > b` e `a == b`.
* (c) Conte quantos `True` existem em cada resultado (use `np.sum(...)`).

Q9 (10 pts) — `astype` com strings numéricas + truncamento

* (a) Crie `numeric_strings = np.array(["1.25", "-9.6", "42"])`.
* (b) Converta para float com `astype(float)` e mostre valores e dtype.
* (c) Converta o resultado para `np.int32` e mostre valores. Em Markdown: descreva o que acontece com a parte decimal.

Q10 (10 pts) — Indexação 2D e 3D

* (a) 2D: com `arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])`, mostre que `arr2d[0][2]` e `arr2d[0, 2]` retornam o mesmo valor.
* (b) 3D: crie `arr3d = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])`.

  * Mostre `arr3d[0]` e seu `shape`.
  * Mostre `arr3d[1, 0]` e seu `shape`.
  * Faça `old = arr3d[0].copy()`; depois `arr3d[0] = 42`; em seguida restaure `arr3d[0] = old`. Mostre o array em cada etapa.

Obs: Poderemos ter variáveis que usarão o mesmo "nome", porém sse estiver em outra questão QX, poderá ou não ter o mesmo significado. Se houver reatribuição de valor o último valor deverá ser levado em conta;

In [1]:
# imports
import numpy as np

## C04B01 Respostas Avaliação de Bloco

---

Q1) Reprodutibilidade com seed

In [2]:
# a)
np.random.seed(123)

data1 = np.random.randn(2, 3)
data1

array([[-1.0856306 ,  0.99734545,  0.2829785 ],
       [-1.50629471, -0.57860025,  1.65143654]])

In [3]:
# b)
np.random.seed(123)

data2 = np.random.randn(2, 3)
data2

array([[-1.0856306 ,  0.99734545,  0.2829785 ],
       [-1.50629471, -0.57860025,  1.65143654]])

In [4]:
# c)
data1 == data2

array([[ True,  True,  True],
       [ True,  True,  True]])

In [5]:
# d)
np.random.seed(321)
data3 = np.random.randn(2, 3)

data3 == data1

array([[False, False, False],
       [False, False, False]])

---

Q2) Inferência de dtype e casting na criação

In [6]:
# a)
arr = np.array([6, 7.5, 8, 0, 1])
arr

array([6. , 7.5, 8. , 0. , 1. ])

In [7]:
arr.dtype

dtype('float64')

b) Quando criamos um array numérico que contenha int e float, NumPy infere o dtype a float que possui uma maior precisão, assim não havendo perda; Existe uma hierarquia de tipos (bool -> int -> float -> complex -> object);

In [8]:
# c)
arr_int = np.array([6, 7.5, 8, 0, 1], dtype=np.int32)
arr_int

array([6, 7, 8, 0, 1], dtype=int32)

Quando inferimos o dtype do array para int e existe algum elemento do tipo float, NumPy faz o Cast de float -> int, truncando o mesmo (retirando valores pós .), ele não arredonda;

---

Q3) Criação: zeros/ones/empty

In [9]:
# a)
z = np.zeros((3, 6))
z

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
o = np.ones(10)
o

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
e = np.empty((2, 3, 2))
e

array([[[          nan,  1.61886e-319],
        [          nan,  3.23781e-319],
        [-0.00000e+000,  8.09477e-320]],

       [[-0.00000e+000,  8.06315e-320],
        [-0.00000e+000,  4.94066e-324],
        [ 4.94066e-324,  0.00000e+000]]])

In [12]:
# b)
print(f"Array z:\nshape: {z.shape}\nndim: {z.ndim}\ndtype: {z.dtype}")

Array z:
shape: (3, 6)
ndim: 2
dtype: float64


In [13]:
print(f"Array o:\nshape: {o.shape}\nndim: {o.ndim}\ndtype: {o.dtype}")

Array o:
shape: (10,)
ndim: 1
dtype: float64


In [14]:
print(f"Array e:\nshape: {e.shape}\nndim: {e.ndim}\ndtype: {e.dtype}")

Array e:
shape: (2, 3, 2)
ndim: 3
dtype: float64


c) np.empty faz sentido quando queremos inicializar um array "vazio" que iremos preencher (devemos); porém caso nã haja total preenchimento ou necessidade existe um custo de memória além de dados "lixos";

---

Q4) `arange` + slicing + atribuição por slice

In [15]:
# a)
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
# b)
arr[5:8] = 12

In [17]:
# c)
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9, 10, 11, 12, 13, 14])

Quando atribuimos um valor a um slice (fatia) de um array aquele valor irá se propagar e refletirá no array original, slice são "views" do array original, ou seja, apontam para a refrência inicial;

---

Q5) View vs copy

In [18]:
# a)
a = np.arange(10)

s = a[2:6]
s[:] = -1

In [19]:
a

array([ 0,  1, -1, -1, -1, -1,  6,  7,  8,  9])

In [20]:
s

array([-1, -1, -1, -1])

In [21]:
# b)
b = np.arange(10)

t = b[2:6].copy()
t[:] = -1

In [22]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
t

array([-1, -1, -1, -1])

c) Quanto reatribuimos `s` com um valor, sendo `s` uma view de `a`, mudamos também os valores referentes em `a`. Já em `b` atribuímos a `t` uma cópia de uma fatia de `b`, onde não existe referência ao array original `b`, sendo assim ao reatribuímos `t` não estamos fazendo nada com `b`;

---

Q6) Aritmética vetorizada

In [24]:
v = np.array([1, 2, 3, 4])

In [25]:
# a)
v * v

array([ 1,  4,  9, 16])

In [26]:
# b)
v - v

array([0, 0, 0, 0])

In [27]:
# c)
1 / v

array([1.        , 0.5       , 0.33333333, 0.25      ])

In [28]:
# d)
v**0.5

array([1.        , 1.41421356, 1.73205081, 2.        ])

---

Q7) Operações com escalares em 2D

In [29]:
# a)
m = np.array([[1, 2, 3], [4, 5, 6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# b)
m + 10

array([[11, 12, 13],
       [14, 15, 16]])

In [31]:
m * 0.1

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

In [32]:
# c)
(m + 10).shape

(2, 3)

In [33]:
(m * 0.1).shape

(2, 3)

---

Q8) Comparações elemento-a-elemento

In [34]:
# a)
a = np.array([[1, 2, 3], [4, 5, 6]])

b = np.array([[0, 2, 4], [4, 4, 7]])

In [35]:
# b)
a > b

array([[ True, False, False],
       [False,  True, False]])

In [36]:
a == b

array([[False,  True, False],
       [ True, False, False]])

In [37]:
# c)
np.sum(a > b)

np.int64(2)

In [38]:
np.sum(a == b)

np.int64(2)

---

Q9) `astype` com strings numéricos + truncamento

In [39]:
# a)
numeric_strings = np.array(["1.25", "-9.6", "42"])
numeric_strings

array(['1.25', '-9.6', '42'], dtype='<U4')

In [40]:
# b)
numeric = numeric_strings.astype(float)
numeric

array([ 1.25, -9.6 , 42.  ])

In [41]:
numeric.dtype

dtype('float64')

In [42]:
# c)
numeric.astype(np.int32)

array([ 1, -9, 42], dtype=int32)

Há um truncamento dos valore float;

---

Q10) Indexação 2D e 3D

In [43]:
# a)
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [44]:
arr2d[0][2] == arr2d[0, 2]

np.True_

In [45]:
# b)
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [46]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
arr3d[0].shape

(2, 3)

In [48]:
arr3d[1, 0]

array([7, 8, 9])

In [49]:
arr3d[1, 0].shape

(3,)

In [50]:
old = arr3d[0].copy()
old

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [52]:
arr3d[0] = 42
old

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [54]:
arr3d[0] = old
old

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])